### ISSUE TITLE
running in docker on M1

### ISSUE THREAD

**Issue by kapps7** [jnewland/hlstube#24]
Hi I am getting this message and an exclamation mark on the image in docker when trying to install this on a M1 machine.
Thanks
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

**Comment by jnewland** [comment]
Fixed by https://github.com/jnewland/hlstube/pull/26
